<?php return array (
  'igniter\\cart\\Extension' => 'extensions/igniter/cart/Extension.php',
  'igniter\\coupons\\Extension' => 'extensions/igniter/coupons/Extension.php',
  'igniter\\demo\\Extension' => 'extensions/igniter/demo/Extension.php',
  'igniter\\frontend\\Extension' => 'extensions/igniter/frontend/Extension.php',
  'igniter\\local\\Extension' => 'extensions/igniter/local/Extension.php',
  'igniter\\pages\\Extension' => 'extensions/igniter/pages/Extension.php',
  'igniter\\payregister\\Extension' => 'extensions/igniter/payregister/Extension.php',
  'igniter\\reservation\\Extension' => 'extensions/igniter/reservation/Extension.php',
  'igniter\\translate\\Extension' => 'extensions/igniter/translate/Extension.php',
  'igniter\\user\\Extension' => 'extensions/igniter/user/Extension.php',
  'Igniter\\Local\\Listeners\\ExtendLocationOptions' => 'extensions/igniter/local/listeners/ExtendLocationOptions.php',
  'Igniter\\Local\\Listeners\\MaxOrderPerTimeslotReached' => 'extensions/igniter/local/listeners/MaxOrderPerTimeslotReached.php',
  'Igniter\\Reservation\\Listeners\\MaxGuestSizePerTimeslotReached' => 'extensions/igniter/reservation/listeners/MaxGuestSizePerTimeslotReached.php',
  'Igniter\\Translate\\Classes\\EventRegistry' => 'extensions/igniter/translate/classes/EventRegistry.php',
  'Igniter\\Pages\\Models\\MenuItem' => 'extensions/igniter/pages/models/MenuItem.php',
  'Igniter\\Pages\\Models\\Pages_model' => 'extensions/igniter/pages/models/Pages_model.php',
  'Igniter\\Translate\\Actions\\TranslatableAction' => 'extensions/igniter/translate/actions/TranslatableAction.php',
  'Igniter\\Translate\\Actions\\TranslatableModel' => 'extensions/igniter/translate/actions/TranslatableModel.php',
  'Igniter\\Cart\\ActivityTypes\\OrderCreated' => 'extensions/igniter/cart/activitytypes/OrderCreated.php',
  'Igniter\\Reservation\\ActivityTypes\\ReservationCreated' => 'extensions/igniter/reservation/activitytypes/ReservationCreated.php',
  'Igniter\\User\\ActivityTypes\\CustomerRegistered' => 'extensions/igniter/user/activitytypes/CustomerRegistered.php',
  'Igniter\\Cart\\Actions\\OrderAction' => 'extensions/igniter/cart/actions/OrderAction.php',
  'Igniter\\Coupons\\Actions\\RedeemsCoupon' => 'extensions/igniter/coupons/actions/RedeemsCoupon.php',
  'igniter\\local\\Controllers\\reviews' => 'extensions/igniter/local/controllers/reviews.php',
  'Igniter\\Local\\Models\\Reviews_model' => 'extensions/igniter/local/models/Reviews_model.php',
  'Igniter\\Local\\Models\\ReviewSettings' => 'extensions/igniter/local/models/ReviewSettings.php',
);